<a href="https://colab.research.google.com/github/nbonair/SIT320-Algorithm/blob/main/computational.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install pulp


Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/
     |████████████████████████████████| 14.2 MB 3.7 MB/s 


In [2]:
from pulp import *

In [41]:
prob = LpProblem("Ex1",LpMinimize)
import numpy as np
# constraints
C = np.array([-1,-2,0,2,2,3,1,-2,1,2,3,3,-2])
x = []
#integer constraint
for i in range(len(C)):
    x.append(LpVariable("x"+str(i), lowBound=0, upBound=1, cat='Integer'))
print(x)
x = np.array(x)

#objective func
prob += np.matmul(C,x)
#Constraint
A = [[2,-1,2,5,-2,3,0,-2,2,-1,-1,0,1],
     [1,1,1,3,2,5,-2,2,5,0,2,3,5],
     [5,4,-2,3,0,0,4,-2,5,3,3,5,-2],
     [4,0,5,-2,-2,0,3,1,0,5,3,0,-2],
     [-2,-1,4,3,-2,-2,0,5,5,-2,-2,2,5]]
A  = np.array(A)
b =np.array( [9.4,19.6,9.6,1.5,11.1])
print(A)
for i in range(len(b)):
    prob+= np.matmul(A[i],x) <= b[i]
print(prob)
status = prob.solve()
print("Lp current status: ",LpStatus[status])
print("Result")
for i in range(len(x)):
    print(int(value(x[i])), end = " ")
print( value(prob.objective))

[x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12]
[[ 2 -1  2  5 -2  3  0 -2  2 -1 -1  0  1]
 [ 1  1  1  3  2  5 -2  2  5  0  2  3  5]
 [ 5  4 -2  3  0  0  4 -2  5  3  3  5 -2]
 [ 4  0  5 -2 -2  0  3  1  0  5  3  0 -2]
 [-2 -1  4  3 -2 -2  0  5  5 -2 -2  2  5]]
Ex1:
MINIMIZE
-1*x0 + -2*x1 + 3*x10 + 3*x11 + -2*x12 + 2*x3 + 2*x4 + 3*x5 + 1*x6 + -2*x7 + 1*x8 + 2*x9 + 0
SUBJECT TO
_C1: 2 x0 - x1 - x10 + x12 + 2 x2 + 5 x3 - 2 x4 + 3 x5 - 2 x7 + 2 x8 - x9
 <= 9.4

_C2: x0 + x1 + 2 x10 + 3 x11 + 5 x12 + x2 + 3 x3 + 2 x4 + 5 x5 - 2 x6 + 2 x7
 + 5 x8 <= 19.6

_C3: 5 x0 + 4 x1 + 3 x10 + 5 x11 - 2 x12 - 2 x2 + 3 x3 + 4 x6 - 2 x7 + 5 x8
 + 3 x9 <= 9.6

_C4: 4 x0 + 3 x10 - 2 x12 + 5 x2 - 2 x3 - 2 x4 + 3 x6 + x7 + 5 x9 <= 1.5

_C5: - 2 x0 - x1 - 2 x10 + 2 x11 + 5 x12 + 4 x2 + 3 x3 - 2 x4 - 2 x5 + 5 x7
 + 5 x8 - 2 x9 <= 11.1

VARIABLES
0 <= x0 <= 1 Integer
0 <= x1 <= 1 Integer
0 <= x10 <= 1 Integer
0 <= x11 <= 1 Integer
0 <= x12 <= 1 Integer
0 <= x2 <= 1 Integer
0 <= x3 <= 1 Integer
0 <= x4 <= 1

In [46]:
prob = LpProblem("Ex2",LpMaximize)
import numpy as np
# constraints
C = np.array([5,2,4,-1,-2,0,-2,-1,-2,-1,-2,-2,0,5,3])

x = []
#integer constraint
for i in range(len(C)):
    x.append(LpVariable("x"+str(i), lowBound=0, upBound = 10))
print(x)
x = np.array(x)

#objective func
prob += np.matmul(C,x)
#Constraint
A = [[1,3,5,0,5,-1,4,4,4,-2,2,0,4,2,-1],
     [5,3,2,4,-2,1,0,3,-2,-2,5,0,-2,0,-2],
     [2,2,5,-2,3,0,-2,1,4,0,4,4,-2,2,1],
     [5,-1,3,2,-2,-1,4,5,0,4,4,4,4,5,2],
     [4,4,3,-1,1,4,3,2,-2,5,-2,5,1,-2,-1]]
A  = np.array(A)
b =np.array( [101,101,72,157,114])
print(A)
for i in range(len(b)):
    prob+= np.matmul(A[i],x) <= b[i]
print(prob)
status = prob.solve()
print("Lp current status: ",LpStatus[status])
print("Result")
for i in range(len(x)):
    print(int(value(x[i])), end = " ")
print()
print( "objective function: ",value(prob.objective))

[x0, x1, x2, x3, x4, x5, x6, x7, x8, x9, x10, x11, x12, x13, x14]
[[ 1  3  5  0  5 -1  4  4  4 -2  2  0  4  2 -1]
 [ 5  3  2  4 -2  1  0  3 -2 -2  5  0 -2  0 -2]
 [ 2  2  5 -2  3  0 -2  1  4  0  4  4 -2  2  1]
 [ 5 -1  3  2 -2 -1  4  5  0  4  4  4  4  5  2]
 [ 4  4  3 -1  1  4  3  2 -2  5 -2  5  1 -2 -1]]
Ex2:
MAXIMIZE
5*x0 + 2*x1 + -2*x10 + -2*x11 + 5*x13 + 3*x14 + 4*x2 + -1*x3 + -2*x4 + -2*x6 + -1*x7 + -2*x8 + -1*x9 + 0
SUBJECT TO
_C1: x0 + 3 x1 + 2 x10 + 4 x12 + 2 x13 - x14 + 5 x2 + 5 x4 - x5 + 4 x6 + 4 x7
 + 4 x8 - 2 x9 <= 101

_C2: 5 x0 + 3 x1 + 5 x10 - 2 x12 - 2 x14 + 2 x2 + 4 x3 - 2 x4 + x5 + 3 x7
 - 2 x8 - 2 x9 <= 101

_C3: 2 x0 + 2 x1 + 4 x10 + 4 x11 - 2 x12 + 2 x13 + x14 + 5 x2 - 2 x3 + 3 x4
 - 2 x6 + x7 + 4 x8 <= 72

_C4: 5 x0 - x1 + 4 x10 + 4 x11 + 4 x12 + 5 x13 + 2 x14 + 3 x2 + 2 x3 - 2 x4
 - x5 + 4 x6 + 5 x7 + 4 x9 <= 157

_C5: 4 x0 + 4 x1 - 2 x10 + 5 x11 + x12 - 2 x13 - x14 + 3 x2 - x3 + x4 + 4 x5
 + 3 x6 + 2 x7 - 2 x8 + 5 x9 <= 114

VARIABLES
x0 <= 10 Continuous
x1 <= 1